In [ ]:
import pandas as pd
import numpy as np

print("Python & Pandas Task 1.1 Started Successfully!")

Python & Pandas Task 1.1 Started Successfully!

In [ ]:
data = {
    "Name": ["Arun", "Bala", "Chandru", "Deepak"],
    "Age": [20, 21, 19, 22],
    "Marks": [85, 78, 92, 74]
}

df = pd.DataFrame(data)

df

      Name  Age  Marks
0     Arun   20     85
1     Bala   21     78
2  Chandru   19     92
3   Deepak   22     74

In [ ]:
df["Name"]

0       Arun
1       Bala
2    Chandru
3     Deepak
Name: Name, dtype: object

In [ ]:
df[["Name", "Marks"]]

      Name  Marks
0     Arun     85
1     Bala     78
2  Chandru     92
3   Deepak     74

In [ ]:
df.iloc[0]

Name     Arun
Age        20
Marks      85
Name: 0, dtype: object

In [ ]:
df.iloc[0:3]

      Name  Age  Marks
0     Arun   20     85
1     Bala   21     78
2  Chandru   19     92

In [ ]:
df[df["Marks"] > 80]

      Name  Age  Marks
0     Arun   20     85
2  Chandru   19     92

In [ ]:
students = pd.DataFrame({
    "Student_ID": [1, 2, 3, 4],
    "Name": ["Arun", "Bala", "Chandru", "Deepak"]
})

marks = pd.DataFrame({
    "Student_ID": [1, 2, 3, 4],
    "Marks": [85, 78, 92, 74]
})

print("Students Data:")
display(students)

print("Marks Data:")
display(marks)

Students Data:

   Student_ID     Name
0           1     Arun
1           2     Bala
2           3  Chandru
3           4   Deepak

Marks Data:

   Student_ID  Marks
0           1     85
1           2     78
2           3     92
3           4     74

In [ ]:
merged_df = pd.merge(
    students,
    marks,
    on="Student_ID",
    how="inner"
)

merged_df

   Student_ID     Name  Marks
0           1     Arun     85
1           2     Bala     78
2           3  Chandru     92
3           4   Deepak     74

In [ ]:
left_merged = pd.merge(
    students,
    marks,
    on="Student_ID",
    how="left"
)

left_merged

   Student_ID     Name  Marks
0           1     Arun     85
1           2     Bala     78
2           3  Chandru     92
3           4   Deepak     74

In [ ]:
right_merged = pd.merge(
    students,
    marks,
    on="Student_ID",
    how="right"
)

right_merged

   Student_ID     Name  Marks
0           1     Arun     85
1           2     Bala     78
2           3  Chandru     92
3           4   Deepak     74

In [ ]:
sales = pd.DataFrame({
    "Month": ["Jan", "Feb", "Mar"],
    "Product_A": [100, 120, 140],
    "Product_B": [80, 90, 110]
})

sales

  Month  Product_A  Product_B
0   Jan        100         80
1   Feb        120         90
2   Mar        140        110

In [ ]:
sales = pd.DataFrame({
    "Month": ["Jan", "Feb", "Mar"],
    "Product_A": [100, 120, 140],
    "Product_B": [80, 90, 110]
})

sales

  Month  Product_A  Product_B
0   Jan        100         80
1   Feb        120         90
2   Mar        140        110

In [ ]:
# Create sales data
sales = pd.DataFrame({
    "Month": ["Jan", "Feb", "Mar"],
    "Product_A": [100, 120, 140],
    "Product_B": [80, 90, 110]
})

# Reshape using melt
long_data = pd.melt(
    sales,
    id_vars=["Month"],
    var_name="Product",
    value_name="Sales"
)

# Reshape back using pivot
pivot_data = long_data.pivot(
    index="Month",
    columns="Product",
    values="Sales"
)

pivot_data

Product  Product_A  Product_B
Month
Feb            120         90
Jan            100         80
Mar            140        110

# Conclusion

In this task, I practiced Python and Pandas data manipulation
operations including indexing, merging, and reshaping.

I learned how to:
- Select rows and columns using indexing
- Merge multiple DataFrames
- Reshape data using melt() and pivot()

This task helped me understand the basic data manipulation
techniques used in Data Science and Analytics.